service:
  name: app-frameworks-metrics

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  addonCapabilities:
    handler: functions/hipchat.addonCapabilities
    events:
      - http:
          method: get
          path: addon/capabilities
  addonInstalled:
    handler: functions/hipchat.addonInstalled
    events:
      - http:
          method: post
          path: addon/installed
  addonUninstalled:
    handler: functions/hipchat.addonUninstalled
    events:
      - http:
          method: post
          path: addon/uninstalled
  supportMessageReceived:
    handler: functions/hipchat.supportMessageReceived
    events:
      - http:
          method: post
          path: support-messages
