service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  createRoomWebhook:
    handler: functions/hipchat.createRoomWebhook
    events:
      - http:
          method: post
          path: rooms/{roomId}/webhooks
          request:
            parameters:
              paths:
                roomId: true
  getCapabilitiesDescriptor:
    handler: functions/hipchat.getCapabilitiesDescriptor
    events:
      - http:
          method: post
          path: addon/descriptor
  supportMessageReceived:
    handler: functions/hipchat.supportMessageReceived
    events:
      - http:
          method: post
          path: support-messages
