service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  supportMessageReceived:
    handler: functions/hipchat.supportMessageReceived
    events:
      - http:
          method: post
          path: support-message
  createRoomWebhook:
    handler: functions/hipchat.createRoomWebhook
    events:
      - http:
          method: post
          path: room/webhook
