service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  addonCapabilities:
    handler: functions/hipchat.addonCapabilities
    events:
      - http:
          method: get
          path: addon/capabilities
  supportMessageReceived:
    handler: functions/hipchat.supportMessageReceived
    events:
      - http:
          method: post
          path: support-messages
